config/routes.rb
Rails.application.routes.draw do
  require 'subdomain'
  # require 'sidekiq/web'
  # mount Sidekiq::Web, at: '/sidekiq'
  # namespace :api, defaults: { format: :json } do
  #   namespace :v1 do
  #     resources :feedbacks, only: :create
  #     resources :mobile_users, only: [:update] do
  #       collection do
  #         post :referral
  #         post :register
  #         post :resend_otp
  #         post :login
  #         get :customer_details
  #         post :device_registration
  #       end

  #       member do
  #         post :authenticate_otp
  #       end
  #     end
  #     resources :complaints do
  #       collection do
  #         post :register
  #       end
  #     end
  #     resources :subscriptions, only: [:create, :update] do
  #       collection do
  #         post :customer_subscriptions
  #         post :renew
  #       end
  #       resources :subscription_pauses, only: [:create, :index]
  #     end

  #     resources :subscription_pauses, except: [:create, :index] do
  #       collection do
  #         get :customerwise
  #       end
  #     end

  #     resources :services do
  #       resources :packs, only: [:index] do
  #         resources :plans, only: [:index, :show]
  #       end
  #     end

  #     resources :lists do
  #       collection do
  #         get :categories
  #         get :countries
  #         get :states
  #         get :cities
  #         get :areas
  #         get :localities
  #         get :societies
  #         get :wings
  #         get :group_areas
  #       end
  #     end

  #     resources :faqs, only: [:index] do
  #       collection do
  #         get :categories
  #       end
  #     end
  #     resources :notifications, only: [:index, :show] do
  #       member do
  #         get :viewed
  #       end
  #     end
  #   end
  #   namespace :v2 do
  #     resources :feedbacks, only: :create
  #     resources :mobile_users, only: [:update] do
  #       collection do
  #         post :register
  #         post :resend_otp
  #         post :login
  #         get :customer_details
  #         post :device_registration
  #         get :auth_details
  #         post :number_available
  #       end

  #       member do
  #         post :authenticate_otp
  #       end
  #     end
  #     resources :complaints do
  #       collection do
  #         post :register
  #       end
  #     end
  #     resources :subscriptions, only: [:create, :update] do
  #       collection do
  #         post :customer_subscriptions
  #         post :renew
  #       end
  #       resources :subscription_pauses, only: [:create, :index]
  #     end

  #     resources :subscription_pauses, except: [:create, :index] do
  #       collection do
  #         get :customerwise
  #       end
  #     end

  #     resources :services do
  #       resources :packs, only: [:index] do
  #         resources :plans, only: [:index, :show]
  #       end
  #     end

  #     resources :lists do
  #       collection do
  #         get :categories
  #         get :countries
  #         get :states
  #         get :cities
  #         get :areas
  #         get :localities
  #         get :societies
  #         get :wings
  #         get :group_areas
  #       end
  #     end

  #     resources :faqs, only: [:index] do
  #       collection do
  #         get :categories
  #       end
  #     end
  #     resources :notifications, only: [:index, :show] do
  #       member do
  #         get :viewed
  #       end
  #     end
  #     resources :pay_u_money
  #     resources :payment_histories do
  #       collection do
  #         post :payu_details
  #       end
  #     end
  #   end
  # end

  scope '/admin' do
    devise_for :users
    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      unauthenticated :user do
        root to: 'devise/sessions#new', as: :unauthenticated_root
      end
      authenticated :user do
        root to: 'orders#index', as: :authenticated_root
      end
    end

    # Routes for location management
    resources :wings do
      collection do
        get :list
      end
    end
    resources :societies do
      collection do
        get :list
        post 'Area', to: 'societies#create_area'
        post 'Locality', to: 'societies#create_locality'
      end
    end

    resources :localities do
      collection do
        get :list
      end
    end
    resources :areas do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :cities do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :states do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :countries do
      member do
        get :delete
      end
    end

    # Routes for service management
    resources :services
    resources :plan_products
    resources :packages
    resources :measurements
    resources :plans do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :packs
    resources :products do
      member do
        get :delete
      end
    end
    resources :orders do
      collection do
        get :excel
      end
      member do
        get :paid
      end
    end
    resources :locality_services

    # Routes For User Management
    resources :referrals
    resources :customers do
      get :search, on: :collection
      resources :subscriptions, except: [:index] do
        get :renew
        post :create_renew
      end
      resources :subscription_pauses
    end
    resources :payment_histories, only: [:edit, :update, :destroy]

    # Routes For FAQ
    resources :faq_questions
    resources :faq_categories do
      resources :faq_questions
    end

    # compalint
    resources :complaints
    resources :complaint_categories
    # feedback
    resources :feedback_categories
    resources :feedbacks
    # leads
    resources :leads, except: [:new, :create, :show]

    # invitations
    resources :invitations

    # notifications
    resources :custom_notifications

    # delivery
    resources :deliveries do
      collection do
        get :excel
      end
    end

    #domains
    resources :seasonal_domains
    constraints(Subdomain) do
      match '/' => 'home#index', via: :get
    end
  end

  # authenticated :user do
  root to: 'home#index'
  resources :home, only: [:index] do
    collection do
      post :create_order
      post :register_complaint
      post :calc_price
    end
  end

  # pay_u_money
  resources :pay_u_money, only: [:index]

  match '/payment_success' => 'pay_u_money#payu_success', :via => [:post]
  match '/payment_success' => 'pay_u_money#payu_success', :via => [:get]
  match '/payment_failure' => 'pay_u_money#payu_failure', :via => [:post]
  match '/payment_failure' => 'pay_u_money#payu_failure', :via => [:get]

  match '/payment' => 'pay_u_money#payu', :via => [:get]
  match '/export' => 'pay_u_money#export', :via => [:get]

  match '/complaint' => 'home#complaint', :via => [:get]
  match '/complaint_submitted' => 'home#complaint_submitted', :via => [:get]
  match '/cart' => 'home#cart', :via => [:get]
  match '/review/:id' => 'home#review', :via => [:get]
  match '/contact' => 'home#contact', :via => [:get]
  match '/policies' => 'home#policies', :via => [:get]
  match '/terms' => 'home#terms', :via => [:get]
  match '/selected_areas' => 'home#selected_areas', :via => [:get]

  # for site down path
  # root to: 'home#index'
  # get '*path', to: 'home#index'
end

app/models/faq_category.rb
# Model for Faq Category
class FaqCategory < ActiveRecord::Base
  belongs_to :service
  has_many :faq_questions

  scope :active, -> { where(is_active: true) }
  scope :inactive, -> { where(is_active: false) }

  validates :name, :description, :service_id, presence: true
end

app/controllers/faq_categories_controller.rb
# Controller for FAQ Category
class FaqCategoriesController < ApplicationController
  before_action :set_faq_category, only: [:show, :edit, :update, :destroy]
  before_action :set_service, except: [:destroy]
  before_action :pagination_params, only: [:index]

  def index
    @faq_categories = FaqCategory.paginate(page: @page, per_page: @per_page)
  end

  def show
  end

  def new
    @faq_category = FaqCategory.new
  end

  def edit
  end

  def create
    @faq_category = FaqCategory.new(faq_category_params)
    notice = 'Faq category was successfully created.'
    if @faq_category.save
      redirect_to @faq_category, notice: notice
    else
      render :new unless @faq_category.save
    end
  end

  def update
    notice = 'Faq category was successfully updated.'
    if @faq_category.update(faq_category_params)
      redirect_to @faq_category, notice: notice
    else
      render :edit
    end
  end

  def destroy
    @faq_category.destroy
    redirect_to faq_categories_url,
                notice: 'Faq category was successfully destroyed.'
  end

  private

  def set_faq_category
    @faq_category = FaqCategory.find(params[:id])
  end

  def faq_category_params
    params.require(:faq_category)
      .permit(
        :name, :service_id, :description, :is_active
      )
  end

  def set_service
    @services = Service.all
  end
end

app/helpers/faq_categories_helper.rb
# Halper for Faq Category
module FaqCategoriesHelper
end

app/views/faq_categories/_form.html.erb
<%= form_for @faq_category, html: { class: 'form-horizontal faq_category' } do |f| %>
    <% if @faq_category.errors.any? %>
    <div id='error_expl' class='panel panel-danger'>
      <div class='panel-heading'>
        <h3 class='panel-title'>
          <%= pluralize(@faq_category.errors.count, 'error') %>
          prohibited this locality from being saved:
        </h3>
      </div>
      <div class='panel-body'>
        <ul>
        <% @faq_category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class='control-group'>
    <%= f.label :service_id, class: 'control-label' %>
    <div class='controls'>
      <%= f.select :service_id,
                   options_from_collection_for_select(@services, 'id', 'name',
                                                      @faq_category.service_id),
                   { prompt: 'Select Service' },{class: 'form-control'} %>
    </div>
    <%= error_span(@faq_category[:service_id]) %>
  </div>


  <div class='control-group'>
    <%= f.label :name, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <%= error_span(@faq_category[:name]) %>
  </div>

  <div class='control-group'>
    <%= f.label :description, class: 'control-label' %>
    <div class='controls'>
      <%= f.cktext_area :description, class: 'form-control' %>
    </div>
    <%= error_span(@faq_category[:description]) %>
  </div>

  <div class='control-group'>
    <%= f.label :is_active, class: 'form-label' %>
    <div class='controls'>
      <%= f.check_box :is_active, class: 'form-control' %>
    </div><br/>
    <%= error_span(@faq_category[:is_active]) %>
  </div>

  <div class='control-group'>
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to t('.cancel',
                    default: t('helpers.links.cancel')),
                    faq_categories_path,
                    class: 'btn btn-default' %>
  </div>
<% end %>

app/views/faq_categories/edit.html.erb
<%- model_class = FaqCategory -%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><%=t '.title',
           default: [:'helpers.titles.edit', 'Edit %{model}'],
           model: model_class.model_name.human.titleize %>
        </h4>
      </div>
      <div class="panel-body">
        <%= render partial: 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/faq_categories/index.html.erb
<%- model_class = FaqCategory -%>
<div class='page-header'>
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>

  <%= link_to t('.new', default: t('helpers.links.new')),
            new_faq_category_path,
            class: 'btn btn-primary' %>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:service_id) %></th>
      <th><%= 'FAQ Count' %></th>
      <th><%= model_class.human_attribute_name(:is_active) %></th>
      <th><%=t '.actions', default: t('helpers.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @faq_categories.each_with_index do |faq_category, index| %>
      <tr>
        <td><%= model_index(index) %></td>
        <td><%= link_to faq_category.name, faq_category_faq_questions_path(faq_category) %></td>
        <td><%= faq_category.service.name unless faq_category.service.nil? %></td>
        <td><%= faq_category.faq_questions.size %></td>
        <td><%= faq_category.is_active %></td>
        <td>
          <%= link_to t('.edit', default: t('helpers.links.edit')),
                      edit_faq_category_path(faq_category), class: 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', default: t('helpers.links.destroy')),
                      faq_category_path(faq_category),
                      method: :delete,
                      data: { confirm: t('.confirm', default: t('helpers.links.confirm', default: 'Are you sure?')) },
                      class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @faq_categories, renderer: BootstrapPagination::Rails %>

app/views/faq_categories/new.html.erb
<%- model_class = FaqCategory -%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><%=t '.title',
           default: [:'helpers.titles.new', 'New %{model}'],
           model: model_class.model_name.human.titleize %>
        </h4>
      </div>
      <div class="panel-body">
        <%= render partial: 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/faq_categories/show.html.erb
<%- model_class = FaqCategory -%>
<div class='page-header'>
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<dl class='dl-horizontal'>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @faq_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @faq_category.description.html_safe %></dd>
  <dt><strong><%= model_class.human_attribute_name(:service_id) %>:</strong></dt>
  <dd><%= @faq_category.service.name if @faq_category.service %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_active) %>:</strong></dt>
  <dd><%= @faq_category.is_active %></dd>
</dl>

<%= link_to t('.back', default: t('helpers.links.back')),
              :back, class: 'btn btn-default'  %>
<%= link_to t('.edit', default: t('helpers.links.edit')),
              edit_faq_category_path(@faq_category), class: 'btn btn-default' %>
<%= link_to t('.destroy', default: t('helpers.links.destroy')),
              faq_category_path(@faq_category),
              method: 'delete',
              data: {
                confirm: t('.confirm',
                           default: t('helpers.links.confirm',
                                      default: 'Are you sure?'))
              },
              class: 'btn btn-danger' %>