config/routes.rb
Rails.application.routes.draw do
  require 'subdomain'
  # require 'sidekiq/web'
  # mount Sidekiq::Web, at: '/sidekiq'
  # namespace :api, defaults: { format: :json } do
  #   namespace :v1 do
  #     resources :feedbacks, only: :create
  #     resources :mobile_users, only: [:update] do
  #       collection do
  #         post :referral
  #         post :register
  #         post :resend_otp
  #         post :login
  #         get :customer_details
  #         post :device_registration
  #       end

  #       member do
  #         post :authenticate_otp
  #       end
  #     end
  #     resources :complaints do
  #       collection do
  #         post :register
  #       end
  #     end
  #     resources :subscriptions, only: [:create, :update] do
  #       collection do
  #         post :customer_subscriptions
  #         post :renew
  #       end
  #       resources :subscription_pauses, only: [:create, :index]
  #     end

  #     resources :subscription_pauses, except: [:create, :index] do
  #       collection do
  #         get :customerwise
  #       end
  #     end

  #     resources :services do
  #       resources :packs, only: [:index] do
  #         resources :plans, only: [:index, :show]
  #       end
  #     end

  #     resources :lists do
  #       collection do
  #         get :categories
  #         get :countries
  #         get :states
  #         get :cities
  #         get :areas
  #         get :localities
  #         get :societies
  #         get :wings
  #         get :group_areas
  #       end
  #     end

  #     resources :faqs, only: [:index] do
  #       collection do
  #         get :categories
  #       end
  #     end
  #     resources :notifications, only: [:index, :show] do
  #       member do
  #         get :viewed
  #       end
  #     end
  #   end
  #   namespace :v2 do
  #     resources :feedbacks, only: :create
  #     resources :mobile_users, only: [:update] do
  #       collection do
  #         post :register
  #         post :resend_otp
  #         post :login
  #         get :customer_details
  #         post :device_registration
  #         get :auth_details
  #         post :number_available
  #       end

  #       member do
  #         post :authenticate_otp
  #       end
  #     end
  #     resources :complaints do
  #       collection do
  #         post :register
  #       end
  #     end
  #     resources :subscriptions, only: [:create, :update] do
  #       collection do
  #         post :customer_subscriptions
  #         post :renew
  #       end
  #       resources :subscription_pauses, only: [:create, :index]
  #     end

  #     resources :subscription_pauses, except: [:create, :index] do
  #       collection do
  #         get :customerwise
  #       end
  #     end

  #     resources :services do
  #       resources :packs, only: [:index] do
  #         resources :plans, only: [:index, :show]
  #       end
  #     end

  #     resources :lists do
  #       collection do
  #         get :categories
  #         get :countries
  #         get :states
  #         get :cities
  #         get :areas
  #         get :localities
  #         get :societies
  #         get :wings
  #         get :group_areas
  #       end
  #     end

  #     resources :faqs, only: [:index] do
  #       collection do
  #         get :categories
  #       end
  #     end
  #     resources :notifications, only: [:index, :show] do
  #       member do
  #         get :viewed
  #       end
  #     end
  #     resources :pay_u_money
  #     resources :payment_histories do
  #       collection do
  #         post :payu_details
  #       end
  #     end
  #   end
  # end

  scope '/admin' do
    devise_for :users
    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      unauthenticated :user do
        root to: 'devise/sessions#new', as: :unauthenticated_root
      end
      authenticated :user do
        root to: 'orders#index', as: :authenticated_root
      end
    end

    # Routes for location management
    resources :wings do
      collection do
        get :list
      end
    end
    resources :societies do
      collection do
        get :list
        post 'Area', to: 'societies#create_area'
        post 'Locality', to: 'societies#create_locality'
      end
    end

    resources :localities do
      collection do
        get :list
      end
    end
    resources :areas do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :cities do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :states do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :countries do
      member do
        get :delete
      end
    end

    # Routes for service management
    resources :services
    resources :plan_products
    resources :packages
    resources :measurements
    resources :plans do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :packs
    resources :products do
      member do
        get :delete
      end
    end
    resources :orders do
      collection do
        get :excel
      end
      member do
        get :paid
      end
    end
    resources :locality_services

    # Routes For User Management
    resources :referrals
    resources :customers do
      get :search, on: :collection
      resources :subscriptions, except: [:index] do
        get :renew
        post :create_renew
      end
      resources :subscription_pauses
    end
    resources :payment_histories, only: [:edit, :update, :destroy]

    # Routes For FAQ
    resources :faq_questions
    resources :faq_categories do
      resources :faq_questions
    end

    # compalint
    resources :complaints
    resources :complaint_categories
    # feedback
    resources :feedback_categories
    resources :feedbacks
    # leads
    resources :leads, except: [:new, :create, :show]

    # invitations
    resources :invitations

    # notifications
    resources :custom_notifications

    # delivery
    resources :deliveries do
      collection do
        get :excel
      end
    end

    #domains
    resources :seasonal_domains
    constraints(Subdomain) do
      match '/' => 'home#index', via: :get
    end
  end

  # authenticated :user do
  root to: 'home#index'
  resources :home, only: [:index] do
    collection do
      post :create_order
      post :register_complaint
      post :calc_price
    end
  end

  # pay_u_money
  resources :pay_u_money, only: [:index]

  match '/payment_success' => 'pay_u_money#payu_success', :via => [:post]
  match '/payment_success' => 'pay_u_money#payu_success', :via => [:get]
  match '/payment_failure' => 'pay_u_money#payu_failure', :via => [:post]
  match '/payment_failure' => 'pay_u_money#payu_failure', :via => [:get]

  match '/payment' => 'pay_u_money#payu', :via => [:get]
  match '/export' => 'pay_u_money#export', :via => [:get]

  match '/complaint' => 'home#complaint', :via => [:get]
  match '/complaint_submitted' => 'home#complaint_submitted', :via => [:get]
  match '/cart' => 'home#cart', :via => [:get]
  match '/review/:id' => 'home#review', :via => [:get]
  match '/contact' => 'home#contact', :via => [:get]
  match '/policies' => 'home#policies', :via => [:get]
  match '/terms' => 'home#terms', :via => [:get]
  match '/selected_areas' => 'home#selected_areas', :via => [:get]

  # for site down path
  # root to: 'home#index'
  # get '*path', to: 'home#index'
end

app/models/plan_product.rb
# == Schema Information
#
# Table name: plan_products
#
#  id             :integer          not null, primary key
#  product_id     :integer
#  package_id     :integer
#  measurement_id :integer
#  date           :date
#  quantity       :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

# Plan Product class
class PlanProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :package
  belongs_to :measurement
  self.per_page = 10
end

app/controllers/plan_products_controller.rb
# plan_product controller for daily packages
class PlanProductsController < ApplicationController
  before_action :set_plan_product, only: [:show, :edit, :update, :destroy]

  def index
    @plan_products = PlanProduct.paginate(page: params[:page])
  end

  def new
    @plan_product = PlanProduct.new
  end

  def create
    @plan_product = PlanProduct.new(plan_product_params)
    respond_to do |format|
      if @plan_product.save
        format.html do
          redirect_to @plan_product, notice: 'Planed Product successfully.'
        end
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @plan_product.update(plan_product_params)
        format.html do
          redirect_to @plan_product,
                      notice: 'Plan product was successfully updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @plan_product.destroy
    respond_to do |format|
      format.html do
        redirect_to plan_products_url,
                    notice: 'Plan product was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_plan_product
    @plan_product = PlanProduct.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white
  # list through.
  def plan_product_params
    params.require(:plan_product)
      .permit(:product_id, :package_id, :measurement_id, :date, :quantity)
  end
end

app/helpers/plan_products_helper.rb
module PlanProductsHelper
end

app/views/plan_products/_form.html.erb
<%= form_for @plan_product, html: { class: 'form-horizontal plan_product' } do |f| %>

  <% if @plan_product.errors.any? %>
    <div id='error_expl' class='panel panel-danger'>
      <div class='panel-heading'>
        <h3 class='panel-title'><%= pluralize(@plan_product.errors.count, 'error') %> prohibited this plan_product from being saved:</h3>
      </div>
      <div class='panel-body'>
        <ul>
        <% @plan_product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class='control-group'>
    <%= f.label :product_id, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :product_id, class: 'form-control' %>
    </div>
    <%= error_span(@plan_product[:product_id]) %>
  </div>

  <div class='control-group'>
    <%= f.label :package_id, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :package_id, class: 'form-control' %>
    </div>
    <%= error_span(@plan_product[:package_id]) %>
  </div>

  <div class='control-group'>
    <%= f.label :measurement_id, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :measurement_id, class: 'form-control' %>
    </div>
    <%= error_span(@plan_product[:measurement_id]) %>
  </div>

  <div class='control-group'>
    <%= f.label :date, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :date, class: 'form-control' %>
    </div>
    <%= error_span(@plan_product[:date]) %>
  </div>

  <div class='control-group'>
    <%= f.label :quantity, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :quantity, class: 'form-control' %>
    </div>
    <%= error_span(@plan_product[:quantity]) %>
  </div>


  <%= f.submit nil, class: 'btn btn-primary' %>
  <%= link_to t('.cancel', default: t('helpers.links.cancel')),
            plan_products_path, class: 'btn btn-default' %>

<% end %>

app/views/plan_products/edit.html.erb
<%- model_class = PlanProduct -%>
<div class='page-header'>
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/plan_products/index.html.erb
<%- model_class = PlanProduct -%>
<div class='page-header'>
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:package_id) %></th>
      <th><%= model_class.human_attribute_name(:measurement_id) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%=t '.actions', default: t('helpers.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @plan_products.each do |plan_product| %>
      <tr>
        <td><%= link_to plan_product.id, plan_product_path(plan_product) %></td>
        <td><%= plan_product.product_id %></td>
        <td><%= plan_product.package_id %></td>
        <td><%= plan_product.measurement_id %></td>
        <td><%= plan_product.date %></td>
        <td><%= plan_product.quantity %></td>
        <td>
          <%= link_to t('.edit', default: t('helpers.links.edit')),
                      edit_plan_product_path(plan_product), class: 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', default: t('helpers.links.destroy')),
                      plan_product_path(plan_product),
                      method: :delete,
                      data: { confirm: t('.confirm', default: t('helpers.links.confirm', default: 'Are you sure?')) },
                      class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @plan_products, renderer: BootstrapPagination::Rails %>

<%= link_to t('.new', default: t('helpers.links.new')),
            new_plan_product_path,
            class: 'btn btn-primary' %>

app/views/plan_products/new.html.erb
<%- model_class = PlanProduct -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model:
    model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/plan_products/show.html.erb
<%- model_class = PlanProduct -%>
<div class='page-header'>
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<dl class='dl-horizontal'>
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @plan_product.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:package_id) %>:</strong></dt>
  <dd><%= @plan_product.package_id %></dd>
  <dt>
    <strong><%= model_class.human_attribute_name(:measurement_id) %>:</strong></dt>
  <dd><%= @plan_product.measurement_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @plan_product.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @plan_product.quantity %></dd>
</dl>

<%= link_to t('.back', default: t('helpers.links.back')),
              :back, class: 'btn btn-default'  %>
<%= link_to t('.edit', default: t('helpers.links.edit')),
              edit_plan_product_path(@plan_product), class: 'btn btn-default' %>
<%= link_to t('.destroy', default: t('helpers.links.destroy')),
              plan_product_path(@plan_product),
              :method: 'delete',
              data: { confirm: t('.confirm', default: t('helpers.links.confirm',
              default: 'Are you sure?')) },
              class: 'btn btn-danger' %>