config/routes.rb
Rails.application.routes.draw do
  require 'subdomain'
  # require 'sidekiq/web'
  # mount Sidekiq::Web, at: '/sidekiq'
  # namespace :api, defaults: { format: :json } do
  #   namespace :v1 do
  #     resources :feedbacks, only: :create
  #     resources :mobile_users, only: [:update] do
  #       collection do
  #         post :referral
  #         post :register
  #         post :resend_otp
  #         post :login
  #         get :customer_details
  #         post :device_registration
  #       end

  #       member do
  #         post :authenticate_otp
  #       end
  #     end
  #     resources :complaints do
  #       collection do
  #         post :register
  #       end
  #     end
  #     resources :subscriptions, only: [:create, :update] do
  #       collection do
  #         post :customer_subscriptions
  #         post :renew
  #       end
  #       resources :subscription_pauses, only: [:create, :index]
  #     end

  #     resources :subscription_pauses, except: [:create, :index] do
  #       collection do
  #         get :customerwise
  #       end
  #     end

  #     resources :services do
  #       resources :packs, only: [:index] do
  #         resources :plans, only: [:index, :show]
  #       end
  #     end

  #     resources :lists do
  #       collection do
  #         get :categories
  #         get :countries
  #         get :states
  #         get :cities
  #         get :areas
  #         get :localities
  #         get :societies
  #         get :wings
  #         get :group_areas
  #       end
  #     end

  #     resources :faqs, only: [:index] do
  #       collection do
  #         get :categories
  #       end
  #     end
  #     resources :notifications, only: [:index, :show] do
  #       member do
  #         get :viewed
  #       end
  #     end
  #   end
  #   namespace :v2 do
  #     resources :feedbacks, only: :create
  #     resources :mobile_users, only: [:update] do
  #       collection do
  #         post :register
  #         post :resend_otp
  #         post :login
  #         get :customer_details
  #         post :device_registration
  #         get :auth_details
  #         post :number_available
  #       end

  #       member do
  #         post :authenticate_otp
  #       end
  #     end
  #     resources :complaints do
  #       collection do
  #         post :register
  #       end
  #     end
  #     resources :subscriptions, only: [:create, :update] do
  #       collection do
  #         post :customer_subscriptions
  #         post :renew
  #       end
  #       resources :subscription_pauses, only: [:create, :index]
  #     end

  #     resources :subscription_pauses, except: [:create, :index] do
  #       collection do
  #         get :customerwise
  #       end
  #     end

  #     resources :services do
  #       resources :packs, only: [:index] do
  #         resources :plans, only: [:index, :show]
  #       end
  #     end

  #     resources :lists do
  #       collection do
  #         get :categories
  #         get :countries
  #         get :states
  #         get :cities
  #         get :areas
  #         get :localities
  #         get :societies
  #         get :wings
  #         get :group_areas
  #       end
  #     end

  #     resources :faqs, only: [:index] do
  #       collection do
  #         get :categories
  #       end
  #     end
  #     resources :notifications, only: [:index, :show] do
  #       member do
  #         get :viewed
  #       end
  #     end
  #     resources :pay_u_money
  #     resources :payment_histories do
  #       collection do
  #         post :payu_details
  #       end
  #     end
  #   end
  # end

  scope '/admin' do
    devise_for :users
    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      unauthenticated :user do
        root to: 'devise/sessions#new', as: :unauthenticated_root
      end
      authenticated :user do
        root to: 'orders#index', as: :authenticated_root
      end
    end

    # Routes for location management
    resources :wings do
      collection do
        get :list
      end
    end
    resources :societies do
      collection do
        get :list
        post 'Area', to: 'societies#create_area'
        post 'Locality', to: 'societies#create_locality'
      end
    end

    resources :localities do
      collection do
        get :list
      end
    end
    resources :areas do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :cities do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :states do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :countries do
      member do
        get :delete
      end
    end

    # Routes for service management
    resources :services
    resources :plan_products
    resources :packages
    resources :measurements
    resources :plans do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :packs
    resources :products do
      member do
        get :delete
      end
    end
    resources :orders do
      collection do
        get :excel
      end
      member do
        get :paid
      end
    end
    resources :locality_services

    # Routes For User Management
    resources :referrals
    resources :customers do
      get :search, on: :collection
      resources :subscriptions, except: [:index] do
        get :renew
        post :create_renew
      end
      resources :subscription_pauses
    end
    resources :payment_histories, only: [:edit, :update, :destroy]

    # Routes For FAQ
    resources :faq_questions
    resources :faq_categories do
      resources :faq_questions
    end

    # compalint
    resources :complaints
    resources :complaint_categories
    # feedback
    resources :feedback_categories
    resources :feedbacks
    # leads
    resources :leads, except: [:new, :create, :show]

    # invitations
    resources :invitations

    # notifications
    resources :custom_notifications

    # delivery
    resources :deliveries do
      collection do
        get :excel
      end
    end

    #domains
    resources :seasonal_domains
    constraints(Subdomain) do
      match '/' => 'home#index', via: :get
    end
  end

  # authenticated :user do
  root to: 'home#index'
  resources :home, only: [:index] do
    collection do
      post :create_order
      post :register_complaint
      post :calc_price
    end
  end

  # pay_u_money
  resources :pay_u_money, only: [:index]

  match '/payment_success' => 'pay_u_money#payu_success', :via => [:post]
  match '/payment_success' => 'pay_u_money#payu_success', :via => [:get]
  match '/payment_failure' => 'pay_u_money#payu_failure', :via => [:post]
  match '/payment_failure' => 'pay_u_money#payu_failure', :via => [:get]

  match '/payment' => 'pay_u_money#payu', :via => [:get]
  match '/export' => 'pay_u_money#export', :via => [:get]

  match '/complaint' => 'home#complaint', :via => [:get]
  match '/complaint_submitted' => 'home#complaint_submitted', :via => [:get]
  match '/cart' => 'home#cart', :via => [:get]
  match '/review/:id' => 'home#review', :via => [:get]
  match '/contact' => 'home#contact', :via => [:get]
  match '/policies' => 'home#policies', :via => [:get]
  match '/terms' => 'home#terms', :via => [:get]
  match '/selected_areas' => 'home#selected_areas', :via => [:get]

  # for site down path
  # root to: 'home#index'
  # get '*path', to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include OrderModule

  before_filter :set_cache_headers
  before_filter :authenticate_user!, except: [:index, :create_order,
    :complaint, :register_complaint, :cart, :review, :calc_price, :contact,
    :terms, :complaint_submitted, :selected_areas, :policies]
    before_filter :create_order_object, only: [:create_order]
  before_filter :load_data, only: [:create_order, :cart]
  skip_before_filter :verify_authenticity_token, :only => [:calc_price]
  before_filter :selected_areas, only: [:cart, :index]

  def index
    @plans = Plan.active.includes(:product).all.where(city_id: params[:city_id])
    #@areas = Area.active.order(:name)
    # html for down site
    # render :down
  end

  def cart
    if params[:plan_id]
      @order = Order.new(plan_id: @plan.id, product_id: @plan.product.id,
        unit: '1', payment_type: '2', status: 'Started')
      @plan = @order.plan
    else
      @order = Order.find(params[:id])
    end
    unit = @order.unit.to_i
    unit = unit
    nprice, ndiscount, ntext = calc_discount(@plan, unit + 1, false)
    #@text = "Buy #{unit + 1} dozens to avail discount worth Rs #{ndiscount.to_i}/-"
    @text = "Buy #{unit + 1} dozen and Save Rs #{ndiscount.to_i}/-"
    redirect_to '/' if @order.status != 'Started'
  end

  def create_order
    respond_to do |format|
      if @order.save
        format.html do
          redirect_to "/review/#{@order.id}?city_id=#{params[:order][:city_id]}"
        end
      else
        unit = @order.unit.to_i
        nprice, ndiscount, ntext = calc_discount(@plan, unit, false)
        @text = "Buy #{unit + 1} dozen and Save Rs #{ndiscount.to_i}/-"
        format.html { render :cart }
      end
    end
  end

  def complaint
    @complaint = Complaint.new
  end

  def register_complaint
    update_complaint_params
    @complaint = Complaint.new(complaint_params)
    if @complaint.save
      redirect_to "/complaint_submitted"
    else
      render :complaint
    end
  end

  def review
    @order = Order.find(params[:id])
    redirect_to '/' if @order.status != 'Started'
  end

  def calc_price
    plan = Plan.find(params[:plan_id])
    unit = params[:unit].to_i
    if plan.product.is_discounted
      price, discount, text = calc_unit(plan, unit)
      render json: { price: price, discount: discount, text: text }
    else
      price = plan.price.to_i * unit
      render json: { price: price, discount: 0, text: text }
    end
  end

  def contact
  end

  def terms
  end

  def policies
  end

  def complaint_submitted
  end

  def selected_areas
    if params[:city_id].present?
      @city = City.find(params[:city_id])
      @areas = @city.areas.order(:name)
    else
      @areas = Area.active.order(:name)
    end
  end

  private

  def load_data
    @products = Product.active
    if params[:plan_id] || params[:order]
      plan_id = params[:plan_id] || params[:order][:plan_id]
      @plan  = Plan.find(plan_id)
    else
      @order = Order.find(params[:id])
      @plan = @order.plan
    end
    @plans = @plan.product.plans
    @areas = Area.active.order(:name)
  end

  def order_params
    params.require(:order).permit(:product_id, :plan_id, :area_id, :user_name,
                                  :address, :mobile_number, :unit,
                                  :payment_type)
  end

  def complaint_params
    params.require(:complaint)
      .permit(:mobile_user_id, :user_id, :complaint_category_id,
              :text, :admin_comment, :status, :is_extra_fruit, :is_resolved,
              :date, :fruit_name, :image, :order_id, :txt_id)
  end

  def update_complaint_params
    order = Order.find_by_txt_id(params[:complaint][:txt_id])
    params[:complaint][:order_id] = order.id if order
  end

  def create_order_object
    if params[:order] && params[:order][:id].present?
      @order = Order.find(params[:order][:id])
      @order.update_attributes(order_params)
    else
      @order = Order.new(order_params)
    end
  end

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def selected_cities(city)
    if city.present?
      @city.name
    end
  end

  def discount_price(price)
    discount = price * 0.10
    (price - discount).to_i
  end
end

app/views/home/cart.html.erb
<div class="desktopLeft" style='background: url("<%= @order.product.side_url %>")'>
  <a href="/home?city_id=<%= params[:city_id]%>" class="circleLogo"></a>
  <h1>
        Fresh &amp; Genuine, Organically Ripened
        <span><%= @order.product.name %></span>
      </h1>
</div>
  <div class="desktopRight">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href="/home?city_id=<%= params[:city_id]%>" class="back"></a>
          <div class="title"><%= @order.product.name %></div>
          </div>
          <div class="btn-group pull-right navBtn">
            <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
            <ul class="dropdown-menu">
              <li><a href="/complaint?city_id=<%= params[:city_id]%>">Add a Complaint</a></li>
            </ul>
          </div>
      </div>
    </nav>
    <div class="banner" style='background: url("<%= @order.product.banner_url %>")'>
      <!-- <h1>Enjoy the Summer <br>
      with Best Quality Mangoes</h1> -->
      <h1>
        Fresh &amp; Genuine, Organically Ripened
        <span><%= @order.product.name %></span>
      </h1>
    </div>
    <div class="container cart">
      <div class="row">
        <div class="col-xs-12 ">
          <%= form_for @order, url: url_for(controller: 'home', action: 'create_order'), method: :post, html: { id: 'order_form' } do |f| %>
            <%= f.hidden_field :product_id, value: f.object.product_id %>
            <%= error_span(@order[:product_id]) %>
            <%= f.hidden_field :id, value: f.object.id %>
            <%= f.hidden_field :plan_id, value: f.object.plan_id %>
            <%= f.hidden_field :city_id, value: params[:city_id] %>
            <div class="formHeading">
              <%= @order.product.name %>
            </div>
            <div class="subHeading">
              Rs <%= @order.plan.price %> / <%= @order.plan.name %>
            </div>
            <div class="form-group clearfix">
              <input class="qButton qtyminus" type="button" value="-">
              <%= f.number_field :unit, placeholder: "Qty.", min: 1, value: (@order.unit.to_i || 1), class: 'form-control moreQuantity qty', readonly: 'readonly' %>
              <%= error_span(@order[:unit]) %>
              <input class="qButton qtyplus" type="button" value="+">
              <div class="priceInfo active">
                <% if @order.unit.to_i <= 1 %>
                  <strike id='base_price'></strike>
                  <span id='price'> Rs. <%= @order.plan.price %>/-</span>
                <% else %>
                  <% if @order.product.is_discounted %>
                    <strike id='base_price'> Rs. <%=  @order.plan.price * @order.unit.to_i %> /-</strike>
                  <% end %>
                  <span id='price'> Rs. <%= @order.price %>/-</span>
                <% end %>
              </div>
            </div>
            <% if f.object.product.is_discounted %>
              <div class="discountWrap active">
                <%= @text %>
              </div>
            <% end %>
            <div class="form-group">
              <div class="selectWrap">
                <%= f.select :area_id, options_from_collection_for_select(@areas, 'id', 'name', @order.area_id), { prompt: 'Select Area' },{class: 'form-control', data: { validation: 'required', validation_error_msg: 'Please Select Area' }} %>
                <label for="order_area_id">Select Area</label>
                <%= error_span_text(@order, :area_id) %>
              </div>
            </div>
            <div class="hideBeforeSelect">
              <div class="form-group">
                <%= f.text_field :user_name, placeholder: "Full Name", class: 'form-control', data: { validation: 'required', validation_error_msg: 'Please enter Full Name' } %>
                <label for="order_user_name">Full Name</label>
                <%= error_span_text(@order, :user_name) %>
              </div>
              <div class="form-group">
                <%= f.text_area :address, placeholder: "Address", class: 'form-control', rows: 3, data: { validation: 'required', validation_error_msg: 'Please enter Address' } %>
                <label for="order_address">Address</label>
                <%= error_span_text(@order, :address) %>
              </div>
              <div class="form-group">
                <%= f.telephone_field :mobile_number, placeholder: "Mobile Number", class: 'form-control', id: 'mobile_number', maxlength: "10", data: { validation: 'number', validation_allowing: 'range[1111111111;9999999999]', validation_error_msg: 'Please enter valid Mobile Number' } %>
                <label for="mobile_number">Mobile Number</label>
                <%= error_span_text(@order, :mobile_number) %>
              </div>
              <div class="list payment radioWrap">
                <div class="heading">Choose Payment Option</div>
                <% PAYMENT_TYPE.each do |str, value| %>
                  <label class="item item-radio">
                    <%= radio_button_tag('order[payment_type]', value, checked = (f.object.payment_type.to_s == value.to_s)) %>

                    <div class="item-content">
                      <%= str %>
                    </div>
                    <i class="radio-icon ion-android-done"></i>
                  </label>
                <% end %>
              </div>
              <div class="deliveryMsg">
                Next day delivery (between 5 - 9 PM)
              </div>

            </div>
            <div class="btnWrap">
            <button type="submit" class="btn btn-block btn-default buyNow active" id='order_button'>
              <i id='saving'>
                <% unless @order.discount.to_i.zero? %>
                  Your Savings: Rs.<%= @order.discount %>/-
                <% end %>
              </i>
              <br> Total:
              <% if @order.price %>
                <span id='price1'>Rs.<%= @order.price %>/-</span>
              <% else %>
                <span id='price1'>Rs.<%= Plan.find(@order.plan_id).price %>/-</span>
              <% end %>
              <span class="btnText">Buy Now</span>
            </button>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/complaint.html.erb
<div class="desktopLeft home">
  <a href="/home?city_id=<%= params[:city_id]%>" class="circleLogo"></a>
  <h1>
    Let the <b>Mango Mania</b> begin...
    <span class="sub">Organically Ripened Alphonso Mangoes</span>
  </h1>
</div>
<div class="desktopRight">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="/home?city_id=<%= params[:city_id]%>" class="back"></a>
        <div class="title">Add Complaint</div>
      </div>
      <div class="btn-group pull-right navBtn">
        <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <ul class="dropdown-menu">
          <li><a href="/complaint?city_id=<%= params[:city_id]%>">Add a Complaint</a></li>
          <!--<li><a href="/terms">Terms &amp; Conditions</a></li>
          <li><a href="/contact">Contact Us</a></li>-->
        </ul>
      </div>
    </div>
  </nav>
  <div class="container complaintWrap">
    <div class="row">
      <div class="col-xs-12">

        <%= form_for @complaint, url: url_for(controller: 'home', action: 'register_complaint'), method: :post, html: { class: 'complain' } do |f| %>
          <%= f.hidden_field :city_id, value: params[:city_id] %>
          <% if @complaint.errors.any? %>
             <div class="alert alert-danger" role="alert">
              <% @complaint.errors.messages.each do |key,value| %>
                <%= value.join(" ") %>
              <% end %>
            </div>
          <% end %>

          <div class='form-group'>
              <%= f.text_field :txt_id, class: 'form-control', placeholder: 'Order ID', data: { validation: 'required', validation_error_msg: 'Please enter Order ID' } %>
              <label for="complaint_txt_id">Order ID</label>
              <%= error_span(@complaint[:txt_id]) %>
          </div>

          <div class='form-group'>
              <%= f.text_area :text, disabled: !f.object.new_record?, cols: 46 , rows: 5, class: 'form-control', placeholder: 'Description', data: { validation: 'required', validation_error_msg: 'Please enter Description' } %>
              <label for="complaint_text">Description</label>
          </div>
          <div class="callUs deliveryMsg">
            For any queries, call us on <a href="tel:+91 88799 89099">+91 88799 89099</a>
          </div>
          <div class="btnWrap">
            <button type="submit" class="btn btn-block btn-default buyNow active" id='order_button'>
              Submit
            </button>
          </div>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/home/complaint_submitted.html.erb
<div class="desktopLeft">
  <a href="/home?city_id=<%= params[:city_id]%>" class="circleLogo"></a>
</div>
<div class="desktopRight">
  <!-- <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="/" class="back"></a>
        <div class="title">Complaint</div>
      </div>
      <div class="btn-group pull-right navBtn">
        <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <ul class="dropdown-menu">
          <li><a href="/complaint">Add a Complaint</a></li>
        </ul>
      </div>
    </div>
  </nav> -->
  <a href="/home?city_id=<%= params[:city_id]%>" class="redClose"></a>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="complaintS">
          <div class="heading">Complaint Submitted</div>
          <p>Thank you for notifying us. We will get in
          touch with you shortly.</p>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/contact.html.erb
<div class="desktopLeft">
  <a href="/home?city_id=<%= params[:city_id]%>" class="circleLogo"></a>
</div>
<div class="desktopRight">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="/home?city_id=<%= params[:city_id]%>" class="back"></a>
        <div class="title">Contact Us</div>
      </div>
      <div class="btn-group pull-right navBtn">
        <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <ul class="dropdown-menu">
          <li><a href="/complaint?city_id=<%= params[:city_id]%>">Add a Complaint</a></li>
          <!--<li><a href="/terms">Terms &amp; Conditions</a></li>
          <li><a href="/contact">Contact Us</a></li>-->
        </ul>
      </div>
    </div>
  </nav>
  <div class="container contentWrap">
    <div class="row">
      <div class="col-xs-12">

     		<p>Get in touch if you have any queries or if you wish to share your feedback. We would be delighted to hear from you!</p>
  		<p>Feel free to ping us on <br>
  		<a href="mailto:buzz@marvelfresh.com">buzz@marvelfresh.com</a></p>
  		<p>Or call us on <a href="tel:+91 88799 89099">+91 88799 89099</a></p>
  		<p>We are located at <br>
  		<span>B/303, Sai Tower, Nr. Old Colony, L.T. Road,
  		Borivli (West), Mumbai 400091</span></p>
      </div>
    </div>
  </div>
</div>

app/views/home/down.html.erb
<a href="http://frools.com"style="height:150px; width:150px; margin:20px auto; display:block; "><img src="/assets/bigLogo.png" height="150" width="150"></a>
<h1 style="position:absolute; top:55%; width:70%; left:15%; text-align:center; font-size:26px; line-height:36px; margin-top:-36px;">Good things don't last forever. And so the Alphonso mango season this year is over. But we will be back next year with same delicious mangoes. Meanwhile Subscribe to Frools Subscriptions. Stay healthy Stay fit. <a href="http://www.frools.com">www.frools.com</a></h1>

app/views/home/review.html.erb
<div class="desktopLeft" style='background: url("<%= @order.product.side_url %>"); background-size: cover;'>
  <a href="/home?city_id=<%= params[:city_id]%>" class="circleLogo"></a>
</div>
<div class="desktopRight">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="/cart?id=<%= @order.id %>&city_id=<%= params[:city_id]%>" class="back"></a>
        <div class="title">Review Your Order</div>
      </div>
      <div class="btn-group pull-right navBtn">
        <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <ul class="dropdown-menu">
          <li><a href="/complaint?city_id=<%= params[:city_id]%>">Add a Complaint</a></li>
          <!--<li><a href="/terms">Terms &amp; Conditions</a></li>
          <li><a href="/contact">Contact Us</a></li>-->
        </ul>
      </div>
    </div>
  </nav>

  <div class="container reviewWrap">
    <div class="row">
      <div class="col-xs-12">
        <div class="rHeading">Delivery Address</div>
        <div class="rInfo"><%= @order.user_name %></div>
        <div class="rInfo"><%= @order.address %></div>
        <div class="rInfo"><%= @order.mobile_number %></div>
        <div class="hr"></div>
        <div class="summary">
          <div class="rHeading">Order summary</div>
          <div class="rInfo rbm">
            <%= @order.product_name %>
          </div>
          <div class="rSmallHeading mb18">
            Rs <%= @order.plan_price %> / <%= @order.plan_unit %>
          </div>
          <div class="row">
            <div class="col-xs-6">
              <div class="rSmallHeading">Qty.</div>
              <div class="rInfo"><%= @order.unit %></div>
            </div>
            <div class="col-xs-6">
              <div class="rSmallHeading">Sub Total</div>
              <div class="rInfo">Rs. <%= @order.plan_price.to_i * @order.unit.to_i %>/-</div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6">
              <div class="rSmallHeading">Discount</div>
              <div class="rInfo">Rs. <%= @order.discount %>/-</div>
            </div>
            <div class="col-xs-6">
              <div class="rSmallHeading">Amount to be paid</div>
              <div class="rInfo bold">Rs. <%= @order.price  %>/-</div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6">
              <div class="rSmallHeading">Delivery Date</div>
              <div class="rInfo"><%= @order.delivery_date.strftime("%d %b %Y") %></div>
            </div>
            <div class="col-xs-6">
              <div class="rSmallHeading">Payment Type</div>
              <div class="rInfo"><%= @order.payment_str %></div>
            </div>
          </div>
        </div>
        <div class="btnWrap">
          <a type="submit" class="btn btn-block btn-default buyNow pay active" href="<%= payment_url + "?id=#{@order.id}" %>">
            Total <br><span>Rs. <%= @order.price %>/-</span>
            <span class="btnText">Proceed to Pay</span>
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/home/selected_areas.html.erb
<div class="desktopLeft">
  <a href="/home?city_id=<%= params[:city_id]%>" class="circleLogo"></a>
</div>
<div class="desktopRight">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="/home?city_id=<%= params[:city_id]%>" class="back"></a>
        <div class="title">Currently Serving in</div>
      </div>
      <!-- <div class="btn-group pull-right navBtn">
        <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <ul class="dropdown-menu">
          <li><a href="/complaint">Add a Complaint</a></li>
        </ul>
      </div> -->
    </div>
  </nav>
  <div class="container contentWrap">
    <div class="row">
      <div class="col-xs-12">
          <div class="complaintS">
            <!-- <div class="heading">Currently Serving in</div> -->
            <p>
            <% @areas.each do |area| %>
              <%= area.name %><br>
            <% end %>
            <!-- Western Mumbai <br>
            Dahisar <br>
            Dahisar East <br>
            Dahisar West <br>
            Borivali <br>
            Borivali East <br>
            Borivali West <br>
            Gorai <br>
            Kandivali <br>
            Kandivali East <br>
            Kandivali West <br>
            Charkop <br>
            Malad <br>
            Malad East <br>
            Malad West <br>
            Goregaon <br>
            Goregaon East <br>
            Goregaon West <br>
            Aarey Colony <br>
            Jogeshwari <br>
            Jogeshwari East <br>
            Jogeshwari West <br>
            JVLR <br>
            Powai <br>
            Andheri <br>
            Andheri East <br>
            Andheri West -->
            </p>
          </div>
    </div>
  </div>
</div>