config/routes.rb
Rails.application.routes.draw do
  require 'subdomain'
  # require 'sidekiq/web'
  # mount Sidekiq::Web, at: '/sidekiq'
  # namespace :api, defaults: { format: :json } do
  #   namespace :v1 do
  #     resources :feedbacks, only: :create
  #     resources :mobile_users, only: [:update] do
  #       collection do
  #         post :referral
  #         post :register
  #         post :resend_otp
  #         post :login
  #         get :customer_details
  #         post :device_registration
  #       end

  #       member do
  #         post :authenticate_otp
  #       end
  #     end
  #     resources :complaints do
  #       collection do
  #         post :register
  #       end
  #     end
  #     resources :subscriptions, only: [:create, :update] do
  #       collection do
  #         post :customer_subscriptions
  #         post :renew
  #       end
  #       resources :subscription_pauses, only: [:create, :index]
  #     end

  #     resources :subscription_pauses, except: [:create, :index] do
  #       collection do
  #         get :customerwise
  #       end
  #     end

  #     resources :services do
  #       resources :packs, only: [:index] do
  #         resources :plans, only: [:index, :show]
  #       end
  #     end

  #     resources :lists do
  #       collection do
  #         get :categories
  #         get :countries
  #         get :states
  #         get :cities
  #         get :areas
  #         get :localities
  #         get :societies
  #         get :wings
  #         get :group_areas
  #       end
  #     end

  #     resources :faqs, only: [:index] do
  #       collection do
  #         get :categories
  #       end
  #     end
  #     resources :notifications, only: [:index, :show] do
  #       member do
  #         get :viewed
  #       end
  #     end
  #   end
  #   namespace :v2 do
  #     resources :feedbacks, only: :create
  #     resources :mobile_users, only: [:update] do
  #       collection do
  #         post :register
  #         post :resend_otp
  #         post :login
  #         get :customer_details
  #         post :device_registration
  #         get :auth_details
  #         post :number_available
  #       end

  #       member do
  #         post :authenticate_otp
  #       end
  #     end
  #     resources :complaints do
  #       collection do
  #         post :register
  #       end
  #     end
  #     resources :subscriptions, only: [:create, :update] do
  #       collection do
  #         post :customer_subscriptions
  #         post :renew
  #       end
  #       resources :subscription_pauses, only: [:create, :index]
  #     end

  #     resources :subscription_pauses, except: [:create, :index] do
  #       collection do
  #         get :customerwise
  #       end
  #     end

  #     resources :services do
  #       resources :packs, only: [:index] do
  #         resources :plans, only: [:index, :show]
  #       end
  #     end

  #     resources :lists do
  #       collection do
  #         get :categories
  #         get :countries
  #         get :states
  #         get :cities
  #         get :areas
  #         get :localities
  #         get :societies
  #         get :wings
  #         get :group_areas
  #       end
  #     end

  #     resources :faqs, only: [:index] do
  #       collection do
  #         get :categories
  #       end
  #     end
  #     resources :notifications, only: [:index, :show] do
  #       member do
  #         get :viewed
  #       end
  #     end
  #     resources :pay_u_money
  #     resources :payment_histories do
  #       collection do
  #         post :payu_details
  #       end
  #     end
  #   end
  # end

  scope '/admin' do
    devise_for :users
    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      unauthenticated :user do
        root to: 'devise/sessions#new', as: :unauthenticated_root
      end
      authenticated :user do
        root to: 'orders#index', as: :authenticated_root
      end
    end

    # Routes for location management
    resources :wings do
      collection do
        get :list
      end
    end
    resources :societies do
      collection do
        get :list
        post 'Area', to: 'societies#create_area'
        post 'Locality', to: 'societies#create_locality'
      end
    end

    resources :localities do
      collection do
        get :list
      end
    end
    resources :areas do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :cities do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :states do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :countries do
      member do
        get :delete
      end
    end

    # Routes for service management
    resources :services
    resources :plan_products
    resources :packages
    resources :measurements
    resources :plans do
      collection do
        get :list
      end
      member do
        get :delete
      end
    end
    resources :packs
    resources :products do
      member do
        get :delete
      end
    end
    resources :orders do
      collection do
        get :excel
      end
      member do
        get :paid
      end
    end
    resources :locality_services

    # Routes For User Management
    resources :referrals
    resources :customers do
      get :search, on: :collection
      resources :subscriptions, except: [:index] do
        get :renew
        post :create_renew
      end
      resources :subscription_pauses
    end
    resources :payment_histories, only: [:edit, :update, :destroy]

    # Routes For FAQ
    resources :faq_questions
    resources :faq_categories do
      resources :faq_questions
    end

    # compalint
    resources :complaints
    resources :complaint_categories
    # feedback
    resources :feedback_categories
    resources :feedbacks
    # leads
    resources :leads, except: [:new, :create, :show]

    # invitations
    resources :invitations

    # notifications
    resources :custom_notifications

    # delivery
    resources :deliveries do
      collection do
        get :excel
      end
    end

    #domains
    resources :seasonal_domains
    constraints(Subdomain) do
      match '/' => 'home#index', via: :get
    end
  end

  # authenticated :user do
  root to: 'home#index'
  resources :home, only: [:index] do
    collection do
      post :create_order
      post :register_complaint
      post :calc_price
    end
  end

  # pay_u_money
  resources :pay_u_money, only: [:index]

  match '/payment_success' => 'pay_u_money#payu_success', :via => [:post]
  match '/payment_success' => 'pay_u_money#payu_success', :via => [:get]
  match '/payment_failure' => 'pay_u_money#payu_failure', :via => [:post]
  match '/payment_failure' => 'pay_u_money#payu_failure', :via => [:get]

  match '/payment' => 'pay_u_money#payu', :via => [:get]
  match '/export' => 'pay_u_money#export', :via => [:get]

  match '/complaint' => 'home#complaint', :via => [:get]
  match '/complaint_submitted' => 'home#complaint_submitted', :via => [:get]
  match '/cart' => 'home#cart', :via => [:get]
  match '/review/:id' => 'home#review', :via => [:get]
  match '/contact' => 'home#contact', :via => [:get]
  match '/policies' => 'home#policies', :via => [:get]
  match '/terms' => 'home#terms', :via => [:get]
  match '/selected_areas' => 'home#selected_areas', :via => [:get]

  # for site down path
  # root to: 'home#index'
  # get '*path', to: 'home#index'
end

app/models/subscription.rb
# Subscription
class Subscription < ActiveRecord::Base
  include SmsGateway
  has_many :subscription_pauses, dependent: :destroy
  has_many :payment_histories, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  belongs_to :plan
  belongs_to :mobile_user

  has_one_time_password length: 6

  validates :plan_id, :start_at, :payment_type, presence: true

  # after_create :send_otp
  before_create :set_start_at
  after_create :set_ends_at
  after_create :create_payment_history

  scope :active, -> { where(is_active: true) }
  scope :inactive, -> { where(is_active: false) }
  scope :deliverable, (lambda do |date|
    where('start_at <= ? AND ends_at >= ?', date, date)
  end)

  def send_otp
    send_sms mobile_number: mobile_user.mobile_number,
             message: message unless mobile_user.is_verified?
  end

  def update_ends_at
    subscription_pauses.count.times do
      self.ends_at += 1.day
      self.ends_at += 1.day if ends_at.wday == 0
    end
    save!
  end

  def month_end?(date)
    date == date.end_of_month
  end

  def self.mark_inactive
    logger.debug '>>>>>>>>>>>>>>>>>>>>>>>>>>> Mark Inactive >>>>>>>>>>>>>>>>>'
    logger.debug ">>>>>>>>>>>>>> Start Time: #{Time.zone.now} >>>>>>>>>>>>>>>>>"
    Subscription.where('ends_at < ?', Time.zone.now.to_date)
      .update_all(is_active: false)
    logger.debug ">>>>>>>>>>>>>> End Time: #{Time.zone.now} >>>>>>>>>>>>>>>>>"
  end

  private

  def message
    SMS_GATEWAY_CONFIG[:otp_messages][:user_app].sub(':otp_code', otp_code)
  end

  def set_start_at
    self.start_at += 1.day if start_at.wday == 0
  end

  def set_ends_at
    if plan.days == 5
      set_week_date
    elsif plan.days == 30
      set_month_date
    end
  end

  def set_week_date
    self.ends_at = start_at
    self.ends_at = add_plan_days(ends_at)
    self.ends_at += 1.day if ends_at.wday == 0
    save!
  end

  def add_plan_days(ends_at)
    plan.days.to_i.times do
      if ends_at.wday == 0
        ends_at += 2.day
      else
        ends_at += 1.day
      end
    end
    ends_at
  end

  def set_month_date
    self.ends_at = calculate_end_date
    self.ends_at -= 1.day if ends_at.wday == 0
    save!
  end

  def calculate_end_date
    if month_end?(start_at)
      ends_at = start_at.next_month.end_of_month
    else
      ends_at = start_at.next_month - 1.day
    end
    ends_at
  end

  def create_payment_history
    payment_histories.create(starts_date: start_at, ends_date: ends_at,
                             is_active: true, subscription_type: 'New',
                             is_paid: payment_type.to_i,
                             payment_type: payment_type)
  end
end

app/controllers/api/v1/subscriptions_controller.rb
module Api
  module V1
    # SubscriptionsController
    class SubscriptionsController < ApiController
      before_action :authenticate_user!
      before_action :actioned, only: [:renew]

      def create
        subscription = Subscription.new(permitted_params)
        subscription.save!
        render json: subscription
      end

      def renew
        subscription = Subscription.find(params[:id])
        subscription.payment_histories.create(
          starts_date: permitted_params[:start_at],
          is_active: false, subscription_type: 'Renew'
        )
        render json: subscription
      end

      def customer_subscriptions
        mobile_user = MobileUser.find_by_mobile_number!(current_mobile_number)
        render json: mobile_user,
               serializer: MySubscriptionSerializer
      end

      def update
        subscription = Subscription.find(params[:id])
        subscription.update_attributes(permitted_params)
        render json: subscription, serializer: UpdateSubscriptionSerializer
      end

      private

      def permitted_params
        params.permit(:id, :mobile_user_id, :plan_id, :start_at, :ends_at,
                      :payment_type, :payment_status, :is_active, :is_paused,
                      :pause_start_date, :pause_end_date)
      end

      def actioned
        return if params[:notification_id].nil?
        notification = Notification.find(params[:notification_id])
        notification.update_attribute(:is_actioned, true)
      end
    end
  end
end

app/controllers/api/v2/subscriptions_controller.rb
module Api
  module V2
    # SubscriptionsController
    class SubscriptionsController < ApiController
      before_action :authenticate_user!
      before_action :actioned, only: [:create]

      def create
        if permitted_params[:payment_type].zero?
          update_subscription
        else
          @subscription = Subscription.find(permitted_params[:subscription_id]) if permitted_params[:subscription_id]
          @mobile_user = MobileUser.find(permitted_params[:mobile_user_id])
        end
        render json: @mobile_user,
               uuid: current_uuid,
               params: params,
               serializer: MobileUserRegisterSerializer
      end

      def customer_subscriptions
        mobile_user = MobileUser.find_by_mobile_number!(current_mobile_number)
        render json: mobile_user,
               serializer: MySubscriptionSerializer
      end

      def update
        subscription = Subscription.find(params[:id])
        subscription.update_attributes(permitted_params)
        render json: subscription, serializer: UpdateSubscriptionSerializer
      end

      private

      def permitted_params
        params.permit(:mobile_user_id, :plan_id, :start_at, :ends_at,
                      :payment_type, :payment_status, :is_active, :is_paused,
                      :pause_start_date, :pause_end_date)
      end

      def actioned
        return if params[:notification_id].nil?
        notification = Notification.find(params[:notification_id])
        notification.update_attribute(:is_actioned, true)
      end

      def update_subscription
        if params[:subscription_id].blank?
          @subscription = Subscription.new(permitted_params)
          @subscription.save!
        else
          @subscription = Subscription.find(params[:subscription_id])
          @subscription.payment_histories.create(
            starts_date: permitted_params[:start_at],
            is_active: false, subscription_type: 'Renew',
            payment_type: permitted_params[:payment_type]
          )
        end
        @mobile_user = @subscription.mobile_user
      end
    end
  end
end

app/controllers/subscriptions_controller.rb
# SubscriptionsController
class SubscriptionsController < ApplicationController
  before_filter :set_pack, except: [:index]
  before_filter :set_subscription, except: [:index, :create, :new, :renew,
                                            :create_renew]

  def new
    @subscription = Subscription.new
    respond_to do |format|
      format.js { render :new }
    end
  end

  def create
    @subscription = Subscription.new(permitted_params)
    @subscription.save
    respond_to do |format|
      format.js { render :create }
    end
  end

  def edit
    respond_to do |format|
      format.js { render :edit }
    end
  end

  def update
    @subscription.update_attributes(permitted_params)
    @subscription.save
    respond_to do |format|
      format.js { render :update }
    end
  end

  def destroy
    @subscription.destroy
    redirect_to customer_url(@subscription.mobile_user),
                notice: 'Subscription was successfully destroyed.'
  end

  def renew
    @subscription = Subscription.find(params[:subscription_id])
    respond_to do |format|
      format.js { render :renew }
    end
  end

  def create_renew
    subscription = Subscription.find(params[:subscription_id])
    subscription.payment_histories.create(
      starts_date: params[:renew][:start_at],
      is_active: false, subscription_type: 'Renew', payment_type: '0')
    respond_to do |format|
      format.js { render :create_renew }
    end
  end

  private

  def set_pack
    @packs = Pack.select('id', 'name').active
  end

  def set_subscription
    @subscription = Subscription.includes(:subscription_pauses,
                                          :payment_histories,
                                          plan: [:pack]).find(params[:id])
  end

  def permitted_params
    params.require(:subscription).permit(:id, :mobile_user_id, :plan_id,
                                         :start_at, :ends_at, :payment_type,
                                         :payment_status, :is_active)
  end
end

app/helpers/subscriptions_helper.rb
# SubscriptionsHelper
module SubscriptionsHelper
  def pay_status(i)
    case i
    when false
      'Unpaid'
    when true
      'Paid'
    end
  end

  def update_link(pay_history)
    if pay_history.is_paid
      link_to 'Update', edit_payment_history_path(id: pay_history.id),
              data: { toggle: 'modal', target: '#pay_status_modal' },
              remote: true, class: 'btn btn-default', disabled: true
    else
      link_to 'Update', edit_payment_history_path(id: pay_history.id),
              data: { toggle: 'modal', target: '#pay_status_modal' },
              remote: true, class: 'btn btn-default'
    end
  end
end

app/views/subscriptions/_edit.html.erb
<%= form_for :subscription, url: "/customers/#{params[:customer_id]}/subscriptions/#{params[:id]}", remote: true, method: :put do |f| %>
  <%= render partial: 'subscription_form', locals: { f: f } %>
<% end %>

app/views/subscriptions/_new.html.erb
<%= form_for :subscription, url: "/customers/#{params[:customer_id]}/subscriptions", remote: true, method: :post do |f| %>
  <%= render partial: 'subscription_form', locals: { f: f } %>
<% end %>

app/views/subscriptions/_payment_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="pay_status_modal" data-backdrop="static"
   data-keyboard="false"  tabindex="-1" role="dialog" aria-labelledby="subscription_label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="subscription_label">Update pay status</h4>
      </div>
      <div class="modal-body payment-update">
        ..
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/_renew_form.html.erb
<%= form_for :renew, url: customer_subscription_create_renew_path(
  customer_id: params[:customer_id], subscription_id: params[:subscription_id]),
  remote: true, method: :post do |f| %>

  <div class='control-group'>
    <%= f.label :start_at, class: 'control-label date-field' %>
    <div class='controls'>
      <%= f.text_field :start_at,
                  class: 'form-control', value: show_date(Date.parse(params[:ends_at])) %>
    </div>
  </div><br/></br>

  <%= f.submit 'Renew', class: 'btn btn-primary ' %></br>
<% end %>

app/views/subscriptions/_subscription_form.html.erb
  <% if @subscription.errors.any? %>
    <div id='error_expl' class='panel panel-danger'>
      <div class='panel-heading'>
        <h3 class='panel-title'>
          <%= pluralize(@subscription.errors.count, 'error') %>
          prohibited from being saved:
        </h3>
      </div>
      <div class='panel-body'>
        <ul>
        <% @subscription.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class='control-group'>
    <%= label_tag nil, 'Pack' , { class: 'control-label'} %>
    <div class='controls'>
    <% if @subscription.plan.nil? %>
      <%= select_tag :subscription_pack_id,
                   options_from_collection_for_select(@packs, 'id', 'name'),
                  { prompt: 'Select pack', class: 'form-control'} %>
    <% else %>
      <%= select_tag :subscription_pack_id,
        options_from_collection_for_select(@packs, 'id', 'name',
          @subscription.plan.pack.id),
            { prompt: 'Select pack', class: 'form-control'}%>
    <% end %>
    </div>
  </div>

  <div class='control-group'>
    <div class='controls'>
      <%= f.hidden_field :mobile_user_id,
                  {class: 'form-control', value: params[:customer_id]} %>
    </div>
  </div>

  <div class='control-group'>
    <%= f.label :plan_id, class: 'control-label' %>
    <div class='controls'>
    <% if @subscription.plan.nil? %>
      <%= f.select :plan_id,{},
        { prompt: 'Select Plan' },{class: 'form-control'} %>
    <% else %>
      <%= f.select :plan_id,
        [
          [@subscription.plan.name,
            @subscription.plan.id]
        ], { prompt: 'Select Plan' },{class: 'form-control'} %>
    <% end %>
    </div>
  </div>

  <div class='control-group'>
    <%= f.label :start_at, class: 'control-label date-field' %>
    <div class='controls'>
      <%= f.text_field :start_at, class: 'form-control date-field' %>
    </div>
  </div>

  <div class='control-group'>
    <%= f.label :payment_type, class: 'control-label' %>
    <div class='controls'>
      <%= f.select :payment_type,
         options_for_payment_type,{}, {class: 'form-control'} %>
    </div>
  </div><br/>

   <!-- <div class='control-group'>
    <%#= f.label :is_active, class: 'control-label' %>
    <div class='controls'>
      <%#= f.check_box :is_active, {class: 'form-control'} %>
    </div>
  </div></br> -->
  </br>
  <%= f.submit nil, class: 'btn btn-primary ' %></br>

app/views/subscriptions/create.js.erb
<% if @subscription.errors.any? %>
  $('.subscription-body').html("<%= j render(partial: 'new') %>")
<% else %>
  location.reload();
<% end %>

app/views/subscriptions/create_renew.js.erb
location.reload();

app/views/subscriptions/edit.js.erb
$('.subscription-body').html("<%= j render(partial: 'edit') %>")

app/views/subscriptions/new.js.erb
$('.subscription-body').html("<%= j render(partial: 'new') %>")

app/views/subscriptions/renew.js.erb
$('.subscription-body').html("<%= j render(partial: 'renew_form') %>")
$('#renew_start_at').datepicker({
  dateFormat: 'dd M yy',
  changeMonth: true,
  changeYear: true,
  minDate: new Date("<%= @subscription.ends_at + 1.days %>"),
  beforeShowDay: function(date){
    var day = date.getDay();
    return [(day !== 0), ''];
  }
});

app/views/subscriptions/show.html.erb
<div class="container">
  <h3><%= link_to @subscription.mobile_user.full_name, customer_path(id: @subscription.mobile_user_id) %></h3>
  <ul class="list-group">
    <li class="list-group-item">
      <span class="pull-left">
        Start Date :  <%= show_date(@subscription.start_at) %>
      </span>
      <span class="pull-right">
        End Date :  <%= show_date(@subscription.ends_at) %>
      </span></br>
    </li>
    <li class="list-group-item">
      <span class="pull-left">
       Pack :  <%= @subscription.plan.pack.name %>
      </span>
      <span class="pull-right">
        Plan : <%= @subscription.plan.name %>
      </span></br>
    </li>
    <li class="list-group-item">
      <span class="pull-left">
       Pause Dates : <%= show_dates(@subscription.subscription_pauses.pluck(:date))%>
      </span>
      </br>
    </li>
  </ul>
</div>
<div class="container">
  <h3>History</h3>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>No. </th>
        <th>Strart Date</th>
        <th>End Date</th>
        <th>Type</th>
        <th>Order ID</th>
        <th>Price</th>
        <th>Payment Type</th>
        <th>Payment Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @subscription.payment_histories.each_with_index do |pay_history, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= show_date(pay_history.starts_date) %></td>
           <td><%= show_date(pay_history.ends_date) %></td>
          <td><%= pay_history.subscription_type %></td>
          <td><%= pay_history.order_id %></td>
          <td><%= pay_history.price %></td>
          <td><%= payment_type(pay_history.payment_type) %></td>
          <td><%= pay_status(pay_history.is_paid) %></td>
          <td>
            <% if pay_history.is_paid %>
              <%= link_to 'Paid', '#', class: 'paid btn btn-default disabled', "data_id": pay_history.id %>
            <% else %>
              <%= link_to 'Paid', "/payment_histories/#{pay_history.id}?is_paid=true", class: 'paid btn btn-default', method: 'patch', "data-confirm": "Are you sure to mark as paid?" %>
            <% end %>
            <%= link_to 'Delete', payment_history_path(pay_history), method: 'delete', "data-confirm":"Are you sure to delete this Payment?", class: 'btn btn-default' if pay_history.subscription_type == 'Renew' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'payment_modal' %>

app/views/subscriptions/update.js.erb
<% if @subscription.errors.any? %>
  $('.subscription-body').html("<%= j render(partial: 'edit') %>")
<% else %>
  location.reload();
<% end %>